title: Hello World
description: A simple application to demonstrate KubeFox.

components:
  hello:
    type: kubefox
    routes:
      - type: http
        match: Path(`/hello`)

  world:
    type: kubefox
